ci: migrate to GitHub Actions
Due to the recent changes to the Travis CI platform (see [1]), we will
now use GitHub Actions to run the tests.

Note: the certificate was updated because it failed with newer Node.js versions

```
_tls_common.js:129
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:129:17)
    at Server.setSecureContext (_tls_wrap.js:1328:27)
```

Reference: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven

[1]: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing